#! /bin/sh

# To make status_of_proc below can be used in the docker container.
. /lib/lsb/init-functions

case "$1" in
  start)
	/usr/local/share/NHIICC/mLNHIICC
	;;
  stop)
	killall mLNHIICC
	;;
  restart)
	killall mLNHIICC
	/usr/local/share/NHIICC/mLNHIICC
	;;

  status)
	status_of_proc -p $RSYNC_PID_FILE "$DAEMON" mLNHIICC
	;;
  *)
	echo "Usage: /etc/init.d/rsync {start|stop|restart|status}"
	exit 1
esac

exit 0
